### ISSUE TITLE
don't work since new version

### ISSUE THREAD

**Issue by nicolas2k** [marccardinal/WheelLog-Garmin-ConnectIQ#1]
Hello

This morning, I've ride and I discover that GApp (Garmin App) was installed on 1.0.10 automatically which don't work : black windows in background and zero everywhere. More infos : test data : blue Windows fixed, Test Http : nothing !

Is it possible to downgrade at 1.0.6 or 1.0.8 to check one component ?

Thanks

**Comment by marccardinal** [comment]
Hi Nicolas, I am working on diagnosing the issue, this is with the 5X Plus?

**Comment by nicolas2k** [comment]
@marccardinal , yes a F5X+ on 7.60.0.0 with GApp 1.0.10 (aug 10th) + wheellog 2.0.23 (aug 08th).
Thanks

**Comment by marccardinal** [comment]
Thanks for the details, I'll try to reproduce on my F3 and in the simulator.

**Comment by nicolas2k** [comment]
have you a new ?
I inform you that all doesn't work nothing at 100% !

**Comment by nicolas2k** [comment]
more infos in MP : done
See you
